# The Docker image that will be used to build your app
image: ubuntu:20.04
create-pages:
  pages:
    # The folder that contains the files to be exposed at the Page URL
    publish: public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == "develop" 
    # $CI_DEFAULT_BRANCH
  # Functions that should be executed before the build script is run
  # libopenblas-dev libfftw3-dev libopenmpi-dev
  script:
    - apt-get install -qq build-essential git gcc gfortran libopenmpi-dev
    - ./configure
