#! /bin/bash
OPT=" -D_FORTRAN_US -D_TEST_MAIN"
#
cd driver/lib
file_list=`find . -maxdepth 1 -type f | grep -E '\.c' |grep -v .swp`
echo $file_list
for file in $file_list; do
 gcc $OPT -c $file -I../include  -I../../include/headers/common 
done
ar -r driver_lib.a *.o
cd ../../

cd driver
gcc $OPT -c driver.c -I include -I options
cp yambo.F yambo.f90
gfortran -c yambo.f90
cd ../

rm -f driver.x
gfortran -o driver.x driver/driver.o driver/yambo.o driver/lib/driver_lib.a

./driver.x -x -J jobA1,jobBBB2 -O ODIRONE -I TESTONE -C COMUNICONE -F input_file -nompi -noopenmp -setup -h

#./driver.x -x -optics c -y d -J jobA1,jobBBB2 -O ODIRONE -I TESTONE -C COMUNICONE -F input_file -t

