#! /bin/bash

PJ=$1
case "${PJ}"
in
e2y) OPT="-D_e2y";;
p2y) OPT="-D_p2y";;
c2y) OPT="-D_c2y";;
a2y) OPT="-D_a2y";;
ph) OPT="-D_ELPH";;
pl) OPT="-D_RT -D_SC -D_ELPH -D_PL";;
sc) OPT="-D_SC";;
rt) OPT="-D_RT -D_ELPH";;
nl) OPT="-D_NL -D_RT -D_ELPH";;
qed) OPT="-D_QED -D_RT -D_ELPH";;
kerr) OPT="-D_RT -D_ELPH -D_KERR";;
m) OPT="-D_MAGNETIC -D_SC";;
e) OPT="-D_ELECTRIC -D_SC";;
esac

LIB="-D_MPI -D_CUDA -D_SCALAPACK -D_SLEPC -D_PAR_IO -D_HDF5_IO -D_HDF5_LIB"

COMP=" -D_FORTRAN_US -D_TEST_MAIN -D_C_US"
#
rm -f driver/lib/*.o driver/lib/*.a driver/interface/*.o driver/include/*.a driver.x

cd driver

cd interface
file_list=`find . -maxdepth 1 -type f | grep -E '\.c' |grep -v .swp`
for file in $file_list; do
 echo $file
 mpicc $COMP $LIB $OPT -c $file -I../include  -I../../include/headers/common 
done
ar -r ../include/driver_lib.a *.o
cd ../

cd lib
file_list=`find . -maxdepth 1 -type f | grep -E '\.c' |grep -v .swp`
for file in $file_list; do
 echo $file
 mpicc $COMP $LIB $OPT -c $file -I../include  -I../../include/headers/common 
done
ar -r ../include/driver_lib.a *.o
cd ../

cd options
file_list=`find . -maxdepth 1 -type f | grep -E '\.c' |grep -v .swp`
for file in $file_list; do
 echo $file
 mpicc $COMP $LIB $OPT -c $file -I../include  -I../../include/headers/common 
done
ar -r ../include/driver_lib.a *.o
cd ../


mpicc $COMP $LIB $OPT -c driver.c -I include -I options -I ../include/headers/common/
cp yambo.F yambo.f90
gfortran -c yambo.f90
cd ../

rm -f driver.x
mpif90 -o driver.x driver/driver.o driver/yambo.o driver/include/driver_lib.a

./driver.x -h
#./driver.x -x -J jobA1,jobBBB2 -O ODIRONE -I TESTONE -C COMUNICONE -F input_file -nompi -noopenmp -setup -opt chi -Q

#./driver.x -x -optics c -y d -J jobA1,jobBBB2 -O ODIRONE -I TESTONE -C COMUNICONE -F input_file -t

