!
!  Copyright (C) 2002-2006 Quantum-ESPRESSO group
!  This file is distributed under the terms of the
!  GNU General Public License. See the file `License'
!  in the root directory of the present distribution,
!  or http://www.gnu.org/copyleft/gpl.txt .
!
#  define DREAL       @@_use_DBLE_instead@@
#  define DIMAG       @@_use_AIMAG_instead@@
#  define DCMPLX      @@_use_CMPLX_instead@@
#  define DFLOAT      @@_use_DBLE_instead@@
#  define CMPLX(a,b)  cmplx(a,b,kind=DP)

#if defined(ADD_BLAS_TWO_UNDERSCORES)
#    define C_NAME(name) name ## __
#elif defined(ADD_BLAS_ONE_UNDERSCORE)
#    define C_NAME(name) name ## _
#else
#    define C_NAME(name) name
#endif

#if defined _DOUBLE
 
#define DAXPY    C_NAME(daxpy)
#define DCOPY    C_NAME(dcopy)
#define DDOT     C_NAME(ddot)
#define DGETRF   C_NAME(dgetrf)
#define DGETRI   C_NAME(dgetri)
#define DGEMV    C_NAME(dgemv)
#define DGEMM    C_NAME(dgemm)
#define DGER     C_NAME(dger)
#define DLASCL   C_NAME(dlascl)
#define DLAE2    C_NAME(dlae2)
#define DLAEV2   C_NAME(dlaev2)
#define DLARTG   C_NAME(dlartg)
#define DLASCL   C_NAME(dlascl)
#define DLANST   C_NAME(dlanst)
#define DLAMCH   C_NAME(dlamch)
#define DLASRT   C_NAME(dlasrt)
#define DLAPY2   C_NAME(dlapy2)
#define DLAPY3   C_NAME(dlapy3)
#define DNRM2    C_NAME(dnrm2)
#define DPOTRF   C_NAME(dpotrf)
#define DPOTRS   C_NAME(dpotrs)
#define DSCAL    C_NAME(dscal)
#define DSPEV    C_NAME(dspev)
#define DSYRK    C_NAME(dsyrk)
#define DSYTRF   C_NAME(dsytrf)
#define DSYTRI   C_NAME(dsytri)
#define DSYEV    C_NAME(dsyev)
#define DSYGV    C_NAME(dsygv)
#define DSYGVX   C_NAME(dsygvx)
#define DSWAP    C_NAME(dswap)
#define DTRTRI   C_NAME(dtrtri)
#define DTRSM    C_NAME(dtrsm)
#define DZNRM2   C_NAME(dznrm2)
#define ILAENV   C_NAME(ilaenv)
#define IDAMAX   C_NAME(idamax)
#define IZAMAX   C_NAME(izamax)
#define ZAXPY    C_NAME(zaxpy)
#define ZCOPY    C_NAME(zcopy)
#define ZDOTC    C_NAME(zdotc)
#define ZDOTU    C_NAME(zdotu)
#define ZGEMM    C_NAME(zgemm)
#define ZGEMV    C_NAME(zgemv)
#define ZGERC    C_NAME(zgerc)
#define ZGESV    C_NAME(zgesv)
#define ZGESVD   C_NAME(zgesvd)
#define ZGGEV    C_NAME(zggev)
#define ZHEEV    C_NAME(zheev)
#define ZHEEVX   C_NAME(zheevx)
#define ZHEGV    C_NAME(zhegv)
#define ZHEGVX   C_NAME(zhegvx)
#define ZHPEV    C_NAME(zhpev)
#define ZHERK    C_NAME(zherk)
#define ZLADIV   C_NAME(zladiv)
#define ZLASET   C_NAME(zlaset)
#define ZPOTF2   C_NAME(zpotf2)
#define ZSCAL    C_NAME(zscal)
#define ZSWAP    C_NAME(zswap)
#define ZTRSM    C_NAME(ztrsm)
#define ZTRTRI   C_NAME(ztrtri)
#define ZDSCAL   C_NAME(zdscal)

#else

#define DAXPY    C_NAME(saxpy)
#define DCOPY    C_NAME(scopy)
#define DDOT     C_NAME(sdot)
#define DGETRF   C_NAME(sgetrf)
#define DGETRI   C_NAME(sgetri)
#define DGEMV    C_NAME(sgemv)
#define DGEMM    C_NAME(sgemm)
#define DGER     C_NAME(sger)
#define DLASCL   C_NAME(slascl)
#define DLAE2    C_NAME(slae2)
#define DLAEV2   C_NAME(slaev2)
#define DLAMCH   C_NAME(slamch)
#define DLANST   C_NAME(slanst)
#define DLARTG   C_NAME(slartg)
#define DLAPY2   C_NAME(slapy2)
#define DLAPY3   C_NAME(slapy3)
#define DLASCL   C_NAME(slascl)
#define DLASRT   C_NAME(slasrt)
#define DNRM2    C_NAME(snrm2)
#define DPOTRF   C_NAME(spotrf)
#define DPOTRS   C_NAME(spotrs)
#define DSCAL    C_NAME(sscal)
#define DSPEV    C_NAME(sspev)
#define DSYRK    C_NAME(ssyrk)
#define DSYTRF   C_NAME(ssytrf)
#define DSYTRI   C_NAME(ssytri)
#define DSYEV    C_NAME(ssyev)
#define DSYGV    C_NAME(ssygv)
#define DSYGVX   C_NAME(ssygvx)
#define DSWAP    C_NAME(sswap)
#define DTRTRI   C_NAME(strtri)
#define DTRSM    C_NAME(strsm)
#define DZNRM2   C_NAME(scnrm2)
#define ILAENV   C_NAME(ilaenv)
#define IDAMAX   C_NAME(idamax)
#define IZAMAX   C_NAME(izamax)
#define ZAXPY    C_NAME(caxpy)
#define ZCOPY    C_NAME(ccopy)
#define ZDOTC    C_NAME(cdotc)
#define ZDOTU    C_NAME(cdotu)
#define ZGEMM    C_NAME(cgemm)
#define ZGEMV    C_NAME(cgemv)
#define ZGERC    C_NAME(cgerc)
#define ZGESV    C_NAME(cgesv)
#define ZGESVD   C_NAME(cgesvd)
#define ZGGEV    C_NAME(cggev)
#define ZHEEV    C_NAME(cheev)
#define ZHEEVX   C_NAME(cheevx)
#define ZHEGV    C_NAME(chegv)
#define ZHEGVX   C_NAME(chegvx)
#define ZHPEV    C_NAME(chpev)
#define ZHERK    C_NAME(cherk)
#define ZLADIV   C_NAME(cladiv)
#define ZLASET   C_NAME(claset)
#define ZPOTF2   C_NAME(cpotf2)
#define ZSCAL    C_NAME(cscal)
#define ZSWAP    C_NAME(cswap)
#define ZTRSM    C_NAME(ctrsm)
#define ZTRTRI   C_NAME(ctrtri)
#define ZDSCAL   C_NAME(csscal)

#endif 
