cpu         = x86_64
os          = linux
mpi         = -D_MPI
netcdf      = -D_HDF5_LIB -D_HDF5_IO
scalapack   = 
slepc       = 
fft         = -D_FFTW
xcpp        = -D_HDF5_LIB -D_HDF5_IO -D_MPI -D_FFTW       -D_TIMING      
keep_objs   = yes
do_blacs    = no
do_slk      = no
do_lapack   = yes
do_fftw     = yes
do_fftqe    = no
do_iotk     = yes
do_futile   = no
do_yaml     = no
do_hdf5     = yes
do_netcdf   = yes
do_etsf     = no
do_p2y      = yes
do_e2y      = no
do_libxc    = yes
do_petsc    = no
do_slepc    = no
shell       = /bin/bash
package_bugreport = yambo@yambo-code.org
prefix      = /home/marini/Yambo/sources/git/yambo/branches/devel-driver-lib
exec_prefix = /home/marini/Yambo/sources/git/yambo/branches/devel-driver-lib
libs_prefix = /home/marini/Yambo/sources/git/yambo/branches/devel-driver-lib/lib/external
bindir      = ${exec_prefix}/bin
topdir      = /home/marini/Yambo/sources/git/yambo/branches/devel-driver-lib
libdir      = /home/marini/Yambo/sources/git/yambo/branches/devel-driver-lib/lib
includedir  = /home/marini/Yambo/sources/git/yambo/branches/devel-driver-lib/include
libbindir   = /home/marini/Yambo/sources/git/yambo/branches/devel-driver-lib/lib/bin
y_version   = "YAMBO 4.5.0 r.18405"
