STDLOG         =/home/marini/Yambo/yambo/branches/devel-compilation/"compile_"HDF5_LIB_HDF5_IO_MPI_FFTW_TIMING_MEM_CHECK".log"
libs           =-L$(libdir)  
linclude       =
lf90libinclude =
lf90include    =
modinclude     =/home/marini/Yambo/yambo/branches/devel-compilation/include
mfiles         =find . -maxdepth 1 -name '*.mod'
precomp_mpi    =yes
precomp_flags  = -D_HDF5_LIB -D_HDF5_IO -D_MPI -D_FFTW -D_TIMING -D_MEM_CHECK -D_$(os)
rm_command     = 
F77_NOOPT_SRC  =xerbla.o slamch.o
FC_NOOPT_SRC   =mod_parser_m.o mod_logo.o
FC_LOCAL_SRC   =sgfft.o
