/*
         Copyright (C) 2000-2019 the YAMBO team
               http://www.yambo-code.org
 
  Authors (see AUTHORS file for details): AM
  
  This file is distributed under the terms of the GNU 
  General Public License. You can redistribute it and/or 
  modify it under the terms of the GNU General Public 
  License as published by the Free Software Foundation; 
  either version 2, or (at your option) any later version.
 
  This program is distributed in the hope that it will 
  be useful, but WITHOUT ANY WARRANTY; without even the 
  implied warranty of MERCHANTABILITY or FITNESS FOR A 
  PARTICULAR PURPOSE.  See the GNU General Public License 
  for more details.
 
  You should have received a copy of the GNU General Public 
  License along with this program; if not, write to the Free 
  Software Foundation, Inc., 59 Temple Place - Suite 330,Boston, 
  MA 02111-1307, USA or visit http://www.gnu.org/copyleft/gpl.txt.

  Command line structure

*/
 static options_struct options[] = { /* Int Real Ch (dummy) Parallel_option*/
#include "common_options.h"
  {"grid","bzgrids","k","BZ Grid generator [(k)pt,(q)pt,(s)hifted,(h)igh symmetry,(r)andom]",0,0,1,0}, 
  {"qpdb","QPDBs",  "q","(g)enerate-modify/(m)erge quasi-particle databases",0,0,1,0}, 
  {"wannier","wannier","i","Wannier 90 interface",0,0,0,0}, 
  {"bxsf","bxsf",   "b","Read BXSF output generated by Wannier90",0,0,0,0},
#if defined _YPP_SC
  {"pot","MeanPot",  "v","Mean Potential",0,0,0,0}, 
#endif
#if defined _YPP_ELPH  
  {"electrons","electrons","s","Electrons [(w)ave,(d)ensity,(m)ag,do(s),(b)ands,(c)urrent,(e)lias]",0,0,1,0}, 
#elif defined _YPP_MAGNETIC 
  {"electrons","electrons","s","Electrons [(w)ave,(d)ensity,(m)ag,do(s),(b)ands,(c)urrent,angu(l)ar,(p)osition]",0,0,1,0}, 
#else
  {"electrons","electrons","s","Electrons [(w)ave,(d)ensity,(m)ag,do(s),(b)ands,(c)urrent]",0,0,1,0}, 
#endif
#if defined _YPP_ELPH  && ! defined _YPP_RT
  {"excitons","excitons", "e","Excitons  [(s)ort,(sp)in,(a)mplitude,(w)ave,(e)lias,(g)kkp]",0,0,1,0}, 
#else
  {"excitons","excitons", "e","Excitons  [(s)ort,(sp)in,(a)mplitude,(w)ave]",0,0,1,0}, 
#endif
  {"freehole","freehole","f","Free hole position [excitons plot]",0,0,0,0}, 
  {"map","kpts_map","m","BZ map fine grid to coarse",0,0,0,0}, 
  {"wf","WFs",     "w","WFs:(p)erturbative SOC mapping or (c)onversion to new I/O format",0,0,1,0},
  {"fixsym","fixsyms", "y","Remove symmetries not consistent with an external perturbation",0,0,0,0},
#if defined _YPP_RT
  {"rtdb","RTDBs",   "c","Carriers [(e)nergy,(k)-space,(f)ermi]",0,0,1,0}, 
  {"rtpol","RealTime","t","TD-polarization [(X)response,Tr(a)bs]",0,0,1,0}, 
  {"rtplot","RealTime","n","NEQ plot opt#1 [(o)ccupations,(l)ifetimes,(d)ensity]",0,0,2,0}, 
  {"NULL","DESC",    " ","         opt#1 o => opt#2 [(b)ands,(t)ime,(e)nergy,(d)os]",0,0,0,0},
  {"NULL","DESC",    " ","         opt#1 l => opt#2 [(b)ands,(t)ime,(e)nergy]",0,0,0,0},
  {"NULL","DESC",    " ","         opt#1 d => opt#2 [(t)ime]",0,0,0,0}, 
#endif
#if defined _YPP_NL
  {"nl","nonlinear","u","Non-linear response analysis",0,0,0,0}, 
#endif
#if defined _YPP_ELPH && ! defined _YPP_RT
  {"phplot","phonons","p","Phonon [(d)os,(e)lias,(a)mplitude]",0,0,1,0}, 
  {"gkkp","gkkp"  , "g","gkkp databases",0,0,0,0}, 
#endif
  {NULL,NULL,NULL,NULL,0,0,0,0}
 };
